name: widgetbook_4
description: Abstract design for the upcoming new major version of Widgetbook.
publish_to: "none"
version: 4.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  widgetbook: ^3.0.0
