/// This file will be generated by widgetbook_generator 4.

part of 'button.stories.dart';

// Syntactic sugar
typedef ButtonScenario = WidgetbookScenario<Button>;

class ButtonStory extends WidgetbookStory<Button, ButtonArgs> {
  ButtonStory({
    required super.name,
    required super.args,
    super.designUrl,
    super.setup,
    super.builder,
  });

  ComponentMetadata get component => ComponentMetadata(
        name: '$Button',
        type: Button,
        description: 'A button to click on.', // From doc comment
      ).mergeWith(metadata);
}

/// A wrapper around the constructor of [Button] that allows to pass
/// [Arg] instead of the constructor arguments.
class ButtonArgs extends WidgetbookArgs<Button> {
  ButtonArgs({
    Arg<String> text = const StringArg(
      '',
      name: 'Text',
      description: 'The text of this button.',
    ),
    Arg<Color> color = const ColorArg(
      Color(0xFF000000),
      name: 'Color',
      description: 'The background color of this button.',
    ),
  })  : this.text = text.mergeWith(
          name: 'Text',
          description: 'The text of this button.',
        ),
        this.color = color.mergeWith(
          name: 'Color',
          description: 'The background color of this button.',
        );

  final Arg<String> text;
  final Arg<Color> color;

  Widget build(BuildContext context) {
    return Button(
      text: text.value,
      color: color.value,
    );
  }
}
