/// This file will be generated by widgetbook_generator 4.

part of 'home_screen.stories.dart';

/// TODO: improve argless stories
class HomeScreenStory extends WidgetbookStory<HomeScreen, HomeScreenArgs> {
  HomeScreenStory({
    required super.name,
    super.args = const HomeScreenArgs(),
    super.setup,
    super.builder,
  });

  ComponentMetadata get component => ComponentMetadata(
        name: '$HomeScreen',
        type: HomeScreen,
      ).mergeWith(metadata);
}

class HomeScreenArgs extends WidgetbookArgs<HomeScreen> {
  const HomeScreenArgs();

  Widget build(BuildContext context) {
    return HomeScreen();
  }
}
